#!/usr/bin/env python3
"""Generate the build-local default secrets header.

The generated header may contain private credentials, so it is written only
under PlatformIO's ignored build directory.
"""

import json
import os
from pathlib import Path

Import("env")

project_dir = Path(env.subst("$PROJECT_DIR"))
build_dir = Path(env.subst("$BUILD_DIR"))
output_dir = build_dir / "generated"
output_path = output_dir / "ws_default_secrets.h"

candidate_paths = []

env_override = os.environ.get("WIPPERSNAPPER_SECRETS_JSON")
if env_override:
    candidate_paths.append(Path(env_override).expanduser())

candidate_paths.extend(
    [
        project_dir / "secrets.json",
        project_dir / "examples" / "secrets-examples" / "secrets.json",
        project_dir / "examples" / "secrets-examples" / "secrets-wifi.json",
    ]
)

source_path = None
for candidate in candidate_paths:
    if not candidate.is_absolute():
        candidate = project_dir / candidate
    if candidate.is_file():
        source_path = candidate
        break

if source_path is None:
    raise RuntimeError("No default secrets JSON source was found")

try:
    secrets_data = json.loads(source_path.read_text(encoding="utf-8"))
except json.JSONDecodeError as exc:
    raise RuntimeError(f"Invalid JSON in {source_path}: {exc}") from exc

if not isinstance(secrets_data, dict):
    raise RuntimeError(f"Default secrets JSON must contain a JSON object: {source_path}")

serialized = json.dumps(secrets_data, indent=2)
escaped = json.dumps(serialized + "\n")

output_dir.mkdir(parents=True, exist_ok=True)
output_path.write_text(
    "\n".join(
        [
            "#pragma once",
            "",
            "// Generated by generate_default_secrets.py.",
            "// This file may contain private credentials and must not be committed.",
            f"static const char WS_DEFAULT_SECRETS_JSON[] = {escaped};",
            "",
        ]
    ),
    encoding="utf-8",
)

env.Append(CPPPATH=[str(output_dir)])

if source_path.name == "secrets.json":
    print(f"Using local default secrets JSON: {source_path}")
else:
    print(f"Using template default secrets JSON: {source_path}")
